# Generated by Django 3.0.5 on 2020-05-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=15)),
                ('collage_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('hobbies', models.CharField(max_length=100)),
            ],
        ),
    ]
